import "./globals.css";
import ServiceRegister from "@/component/register-sw";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest:'/manifest.json',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <meta name="background_color" content="#141414"/>
            <meta name="theme-color" content="#000000"/>
      <body>
        {children}
        <ServiceRegister />
      </body>
    </html>
  );
}
